function ecg_gui_arrhythmia()
    % Create Main Figure (resized to fit all components)
    f = figure('Name', 'ECG Arrhythmia Detector', ...
               'Position', [100, 100, 850, 600], ...
               'Color', 'white');

    %% Heart Rate Display
    hrVal = uicontrol('Style', 'text', ...
                      'String', '---', ...
                      'FontSize', 48, ...
                      'FontWeight', 'bold', ...
                      'ForegroundColor', [246 77 77]/255, ...
                      'BackgroundColor', 'white', ...
                      'Position', [62 440 100 60]);

    uicontrol('Style', 'text', ...
              'String', 'bpm (Beats per minute)', ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0 0 0], ...
              'BackgroundColor', 'white', ...
              'Position', [55 410 150 30]);

    %% Status Label
    uicontrol('Style', 'text', ...
              'String', 'Status:', ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', 'white', ...
              'Position', [480 410 100 30]);

    statusText = uicontrol('Style', 'text', ...
                           'String', '---', ...
                           'FontSize', 16, ...
                           'FontWeight', 'bold', ...
                           'ForegroundColor', [246 77 77]/255, ...
                           'BackgroundColor', 'white', ...
                           'Position', [480 410 200 30]);

    %% Upload Button
    uicontrol('Style', 'pushbutton', ...
              'String', 'Upload ECG', ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [246 77 77]/255, ...
              'ForegroundColor', 'white', ...
              'Position', [480 460 200 50], ...
              'Callback', @uploadECGCallback);

    %% ECG Plot Area
    ax = axes('Parent', f, 'Units', 'pixels', ...
              'Position', [100 50 650 300]);

    %% Callback for ECG Upload
    function uploadECGCallback(~, ~)
        try
            ecg = readmatrix('ecg.csv'); % Uses ecg.csv file
            ecg = ecg(:); % Ensure column vector
            fs = 250;     % Sampling frequency

            % Simple preprocessing and detection
            ecg_filtered = bandpass(ecg, [0.5 45], fs);
            diff_ecg = diff(ecg_filtered); diff_ecg(end+1) = diff_ecg(end);
            squared = diff_ecg.^2;
            integrated = movmean(squared, round(0.150 * fs));
            [~, locs] = findpeaks(integrated, 'MinPeakHeight', 0.001, 'MinPeakDistance', round(0.4 * fs));
            rr_intervals = diff(locs) / fs;
            hr = round(mean(60 ./ rr_intervals));

            % Update Plot
            t = (1:length(ecg_filtered)) / fs;
            plot(ax, t, ecg_filtered, 'b');
            hold on;
            plot(ax, t(locs), ecg_filtered(locs), 'ro');
            xlabel('Time (s)');
            ylabel('Amplitude');
            title('Filtered ECG');

            % Update Heart Rate Display
            set(hrVal, 'String', num2str(hr));

            % Update Status
            if hr < 60
                set(statusText, 'String', 'Bradycardia');
            elseif hr > 100
                set(statusText, 'String', 'Tachycardia');
            else
                set(statusText, 'String', 'Normal');
            end
        catch ME
            disp(['Error loading ECG: ', ME.message]);
        end
    end
end